/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azureglobalservice/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAzureGlobalServices implements AzureGlobalServiceInterface
type FakeAzureGlobalServices struct {
	Fake *FakeAzureglobalservicesV1alpha1
	ns   string
}

var azureglobalservicesResource = schema.GroupVersionResource{Group: "azureglobalservices.networking.aks.io", Version: "v1alpha1", Resource: "azureglobalservices"}

var azureglobalservicesKind = schema.GroupVersionKind{Group: "azureglobalservices.networking.aks.io", Version: "v1alpha1", Kind: "AzureGlobalService"}

// Get takes name of the azureGlobalService, and returns the corresponding azureGlobalService object, and an error if there is any.
func (c *FakeAzureGlobalServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AzureGlobalService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azureglobalservicesResource, c.ns, name), &v1alpha1.AzureGlobalService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureGlobalService), err
}

// List takes label and field selectors, and returns the list of AzureGlobalServices that match those selectors.
func (c *FakeAzureGlobalServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AzureGlobalServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azureglobalservicesResource, azureglobalservicesKind, c.ns, opts), &v1alpha1.AzureGlobalServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AzureGlobalServiceList{ListMeta: obj.(*v1alpha1.AzureGlobalServiceList).ListMeta}
	for _, item := range obj.(*v1alpha1.AzureGlobalServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureGlobalServices.
func (c *FakeAzureGlobalServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azureglobalservicesResource, c.ns, opts))

}

// Create takes the representation of a azureGlobalService and creates it.  Returns the server's representation of the azureGlobalService, and an error, if there is any.
func (c *FakeAzureGlobalServices) Create(ctx context.Context, azureGlobalService *v1alpha1.AzureGlobalService, opts v1.CreateOptions) (result *v1alpha1.AzureGlobalService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azureglobalservicesResource, c.ns, azureGlobalService), &v1alpha1.AzureGlobalService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureGlobalService), err
}

// Update takes the representation of a azureGlobalService and updates it. Returns the server's representation of the azureGlobalService, and an error, if there is any.
func (c *FakeAzureGlobalServices) Update(ctx context.Context, azureGlobalService *v1alpha1.AzureGlobalService, opts v1.UpdateOptions) (result *v1alpha1.AzureGlobalService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azureglobalservicesResource, c.ns, azureGlobalService), &v1alpha1.AzureGlobalService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureGlobalService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAzureGlobalServices) UpdateStatus(ctx context.Context, azureGlobalService *v1alpha1.AzureGlobalService, opts v1.UpdateOptions) (*v1alpha1.AzureGlobalService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(azureglobalservicesResource, "status", c.ns, azureGlobalService), &v1alpha1.AzureGlobalService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureGlobalService), err
}

// Delete takes name of the azureGlobalService and deletes it. Returns an error if one occurs.
func (c *FakeAzureGlobalServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azureglobalservicesResource, c.ns, name), &v1alpha1.AzureGlobalService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureGlobalServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azureglobalservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AzureGlobalServiceList{})
	return err
}

// Patch applies the patch and returns the patched azureGlobalService.
func (c *FakeAzureGlobalServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AzureGlobalService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azureglobalservicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.AzureGlobalService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureGlobalService), err
}
