/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azuremulticlusteringress/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAzureMultiClusterIngresses implements AzureMultiClusterIngressInterface
type FakeAzureMultiClusterIngresses struct {
	Fake *FakeAzuremulticlusteringressesV1alpha1
	ns   string
}

var azuremulticlusteringressesResource = schema.GroupVersionResource{Group: "azuremulticlusteringresses.networking.aks.io", Version: "v1alpha1", Resource: "azuremulticlusteringresses"}

var azuremulticlusteringressesKind = schema.GroupVersionKind{Group: "azuremulticlusteringresses.networking.aks.io", Version: "v1alpha1", Kind: "AzureMultiClusterIngress"}

// Get takes name of the azureMultiClusterIngress, and returns the corresponding azureMultiClusterIngress object, and an error if there is any.
func (c *FakeAzureMultiClusterIngresses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AzureMultiClusterIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(azuremulticlusteringressesResource, c.ns, name), &v1alpha1.AzureMultiClusterIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureMultiClusterIngress), err
}

// List takes label and field selectors, and returns the list of AzureMultiClusterIngresses that match those selectors.
func (c *FakeAzureMultiClusterIngresses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AzureMultiClusterIngressList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(azuremulticlusteringressesResource, azuremulticlusteringressesKind, c.ns, opts), &v1alpha1.AzureMultiClusterIngressList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AzureMultiClusterIngressList{ListMeta: obj.(*v1alpha1.AzureMultiClusterIngressList).ListMeta}
	for _, item := range obj.(*v1alpha1.AzureMultiClusterIngressList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested azureMultiClusterIngresses.
func (c *FakeAzureMultiClusterIngresses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(azuremulticlusteringressesResource, c.ns, opts))

}

// Create takes the representation of a azureMultiClusterIngress and creates it.  Returns the server's representation of the azureMultiClusterIngress, and an error, if there is any.
func (c *FakeAzureMultiClusterIngresses) Create(ctx context.Context, azureMultiClusterIngress *v1alpha1.AzureMultiClusterIngress, opts v1.CreateOptions) (result *v1alpha1.AzureMultiClusterIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(azuremulticlusteringressesResource, c.ns, azureMultiClusterIngress), &v1alpha1.AzureMultiClusterIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureMultiClusterIngress), err
}

// Update takes the representation of a azureMultiClusterIngress and updates it. Returns the server's representation of the azureMultiClusterIngress, and an error, if there is any.
func (c *FakeAzureMultiClusterIngresses) Update(ctx context.Context, azureMultiClusterIngress *v1alpha1.AzureMultiClusterIngress, opts v1.UpdateOptions) (result *v1alpha1.AzureMultiClusterIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(azuremulticlusteringressesResource, c.ns, azureMultiClusterIngress), &v1alpha1.AzureMultiClusterIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureMultiClusterIngress), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAzureMultiClusterIngresses) UpdateStatus(ctx context.Context, azureMultiClusterIngress *v1alpha1.AzureMultiClusterIngress, opts v1.UpdateOptions) (*v1alpha1.AzureMultiClusterIngress, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(azuremulticlusteringressesResource, "status", c.ns, azureMultiClusterIngress), &v1alpha1.AzureMultiClusterIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureMultiClusterIngress), err
}

// Delete takes name of the azureMultiClusterIngress and deletes it. Returns an error if one occurs.
func (c *FakeAzureMultiClusterIngresses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(azuremulticlusteringressesResource, c.ns, name), &v1alpha1.AzureMultiClusterIngress{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAzureMultiClusterIngresses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(azuremulticlusteringressesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AzureMultiClusterIngressList{})
	return err
}

// Patch applies the patch and returns the patched azureMultiClusterIngress.
func (c *FakeAzureMultiClusterIngresses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AzureMultiClusterIngress, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(azuremulticlusteringressesResource, c.ns, name, pt, data, subresources...), &v1alpha1.AzureMultiClusterIngress{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AzureMultiClusterIngress), err
}
