/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	azuremulticlusteringressv1alpha1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/apis/azuremulticlusteringress/v1alpha1"
	versioned "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/azure_multicluster_crd_client/clientset/versioned"
	internalinterfaces "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/azure_multicluster_crd_client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/Azure/application-gateway-kubernetes-ingress/pkg/crd_client/azure_multicluster_crd_client/listers/azuremulticlusteringress/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AzureMultiClusterIngressInformer provides access to a shared informer and lister for
// AzureMultiClusterIngresses.
type AzureMultiClusterIngressInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AzureMultiClusterIngressLister
}

type azureMultiClusterIngressInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAzureMultiClusterIngressInformer constructs a new informer for AzureMultiClusterIngress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAzureMultiClusterIngressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAzureMultiClusterIngressInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAzureMultiClusterIngressInformer constructs a new informer for AzureMultiClusterIngress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAzureMultiClusterIngressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzuremulticlusteringressesV1alpha1().AzureMultiClusterIngresses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzuremulticlusteringressesV1alpha1().AzureMultiClusterIngresses(namespace).Watch(context.TODO(), options)
			},
		},
		&azuremulticlusteringressv1alpha1.AzureMultiClusterIngress{},
		resyncPeriod,
		indexers,
	)
}

func (f *azureMultiClusterIngressInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAzureMultiClusterIngressInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *azureMultiClusterIngressInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&azuremulticlusteringressv1alpha1.AzureMultiClusterIngress{}, f.defaultInformer)
}

func (f *azureMultiClusterIngressInformer) Lister() v1alpha1.AzureMultiClusterIngressLister {
	return v1alpha1.NewAzureMultiClusterIngressLister(f.Informer().GetIndexer())
}
